import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import API from '../api';
import { 
  Sparkles, 
  Activity, 
  Timer, 
  Flame, 
  ChevronRight, 
  Loader2, 
  Dumbbell, 
  Target, 
  ArrowRight,
  TrendingUp,
  User,
  ShieldAlert
} from 'lucide-react';

const AIWorkouts = () => {
  const [loading, setLoading] = useState(false);
  const [plans, setPlans] = useState([]);
  const [error, setError] = useState(null);
  const [formData, setFormData] = useState({
    age: '',
    weight: '',
    height: '',
    goal: 'Muscle Building',
    fitness_level: 'Intermediate',
    sport_interest: 'General Fitness'
  });

  useEffect(() => {
    fetchPlans();
  }, []);

  const fetchPlans = async () => {
    try {
      const { data } = await API.get('/workouts');
      // Show only the latest plan
      setPlans(data.slice(0, 1));
    } catch (err) {
      console.error(err);
    }
  };

  const handleGenerate = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {
      const { data } = await API.post('/workouts/generate', formData);
      // Replace with new plan
      setPlans([data]);
    } catch (err) {
      console.error(err);
      setError(err?.response?.data?.message || 'Neural link failed. Verify parameters and try again.');
    } finally {
      setLoading(false);
    }
  };

  const handleInitialize = async (workoutId) => {
    try {
      const { data } = await API.post(`/workouts/${workoutId}/complete`);
      alert(`SYSTEM ALERT: ${data.message}\nLevel: ${data.new_level} | XP: ${data.new_xp}`);
    } catch (err) {
      console.error(err);
      alert('Failed to initialize sequence. Try again.');
    }
  };

  return (
    <div className="space-y-10 pb-10">
      <div className="space-y-3">
         <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-brand-orange/10 rounded-lg flex items-center justify-center text-brand-orange border border-brand-orange/20">
               <Dumbbell size={18} />
            </div>
            <span className="text-[10px] font-bold text-brand-orange uppercase tracking-[0.3em]">Engine Module</span>
         </div>
         <h2 className="text-4xl md:text-5xl font-black italic tracking-tighter text-white leading-none uppercase">
           AI WORKOUT <span className="text-brand-orange">SYNC</span>
         </h2>
         <p className="text-gray-500 font-bold text-sm uppercase tracking-wide">Personalized hyper-efficient routines generated by elite algorithms.</p>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-12 gap-10">
        {/* Input Form Card */}
        <div className="xl:col-span-4">
          <motion.div 
            initial={{ opacity: 0, x: -20 }}
            animate={{ opacity: 1, x: 0 }}
            className="bg-brand-navy-light rounded-[2.5rem] p-10 border border-white/5 shadow-2xl xl:sticky xl:top-24"
          >
            <div className="mb-8">
               <h3 className="text-2xl font-black text-white italic tracking-tighter uppercase leading-none mb-1.5">Physio Metrics</h3>
               <p className="text-[10px] font-bold text-gray-600 uppercase tracking-widest italic">Calibration required for deployment</p>
            </div>
            
            <form onSubmit={handleGenerate} className="space-y-5">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <label className="text-[10px] font-bold uppercase tracking-widest text-gray-500 ml-1">Age Scope</label>
                  <input
                    type="number"
                    value={formData.age}
                    onChange={(e) => setFormData({...formData, age: e.target.value})}
                    className="w-full bg-black/20 border border-white/10 focus:border-brand-orange/50 rounded-xl p-4 text-sm font-bold text-white outline-none transition-all"
                    placeholder="25"
                    required
                  />
                </div>
                <div className="space-y-2">
                  <label className="text-[10px] font-bold uppercase tracking-widest text-gray-500 ml-1">Mass <span className="text-[8px] opacity-60">(KG)</span></label>
                  <input
                    type="number"
                    value={formData.weight}
                    onChange={(e) => setFormData({...formData, weight: e.target.value})}
                    className="w-full bg-black/20 border border-white/10 focus:border-brand-orange/50 rounded-xl p-4 text-sm font-bold text-white outline-none transition-all"
                    placeholder="75"
                    required
                  />
                </div>
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-bold uppercase tracking-widest text-gray-500 ml-1">Vertical Scale <span className="text-[8px] opacity-60">(CM)</span></label>
                <input
                  type="number"
                  value={formData.height}
                  onChange={(e) => setFormData({...formData, height: e.target.value})}
                  className="w-full bg-black/20 border border-white/10 focus:border-brand-orange/50 rounded-xl p-4 text-sm font-bold text-white outline-none transition-all"
                  placeholder="180"
                  required
                />
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-bold uppercase tracking-widest text-gray-500 ml-1">Mission Objective</label>
                <select
                  value={formData.goal}
                  onChange={(e) => setFormData({...formData, goal: e.target.value})}
                  className="w-full bg-black/20 border border-white/10 focus:border-brand-orange/50 rounded-xl p-4 text-sm font-bold text-white outline-none transition-all cursor-pointer appearance-none"
                >
                  {['Fat Loss', 'Muscle Building', 'Strength', 'Endurance', 'Flexibility'].map(g => (
                    <option key={g} value={g} className="bg-brand-navy-light text-white">{g}</option>
                  ))}
                </select>
              </div>

              <div className="space-y-2">
                <label className="text-[10px] font-bold uppercase tracking-widest text-gray-500 ml-1">Experience Protocol</label>
                <select
                  value={formData.fitness_level}
                  onChange={(e) => setFormData({...formData, fitness_level: e.target.value})}
                  className="w-full bg-black/20 border border-white/10 focus:border-brand-orange/50 rounded-xl p-4 text-sm font-bold text-white outline-none transition-all cursor-pointer appearance-none"
                >
                  {['Beginner', 'Intermediate', 'Advanced', 'Elite'].map(l => (
                    <option key={l} value={l} className="bg-brand-navy-light text-white">{l}</option>
                  ))}
                </select>
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full h-16 bg-brand-orange text-white rounded-xl font-bold text-[11px] uppercase tracking-widest transition-all hover:brightness-110 active:scale-95 flex items-center justify-center gap-3 shadow-orange-glow italic mt-4"
              >
                {loading ? (
                  <> <Loader2 className="animate-spin text-white" size={18} /> CALIBRATING... </>
                ) : (
                  <> <Sparkles size={18} className="text-white" /> GENERATE PROTOCOL </>
                )}
              </button>
            </form>
          </motion.div>
        </div>

        {/* Results List */}
        <div className="xl:col-span-8 space-y-8">
          <AnimatePresence initial={false} mode="popLayout">
            {plans.map((plan, i) => (
              <motion.div
                key={plan.id}
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ duration: 0.4, delay: i * 0.1 }}
                className="bg-brand-navy-light rounded-[2.5rem] border border-white/5 shadow-2xl overflow-hidden group hover:border-brand-orange/20 transition-all"
              >
                <div className="p-8 md:p-12">
                  <div className="flex flex-col xl:flex-row justify-between items-center gap-8 mb-10">
                    <div className="w-full xl:max-w-[60%]">
                      <div className="flex items-center gap-4 mb-4">
                        <span className="px-2.5 py-1 bg-brand-orange/10 border border-brand-orange/20 text-brand-orange rounded text-[8px] font-bold uppercase tracking-widest italic">
                          {plan.fitness_level} SESSION
                        </span>
                        <span className="text-gray-600 text-[8px] font-bold uppercase tracking-widest italic">
                          SYNC: {new Date(plan.created_at).toLocaleDateString().toUpperCase()}
                        </span>
                      </div>
                      <h4 className="text-3xl md:text-4xl xl:text-[2.75rem] font-black text-white italic tracking-tighter uppercase leading-[0.9]">
                         {plan.goal.split(' ')[0]} <span className="text-brand-orange">PROTOCOL</span>
                      </h4>
                    </div>

                    <div className="flex items-center gap-6 md:gap-10 bg-black/20 p-6 rounded-3xl border border-white/5 shadow-inner shrink-0 w-full xl:w-auto justify-center xl:justify-end">
                      <div className="text-center xl:text-left">
                        <p className="text-[8px] uppercase text-gray-500 font-bold tracking-widest mb-1 italic">Est. Calories</p>
                        <p className="text-brand-orange text-2xl font-black italic flex items-center gap-2 justify-center xl:justify-start leading-none">
                          <Flame size={18} fill="currentColor" strokeWidth={0} /> {plan.estimated_calories}
                        </p>
                      </div>
                      <div className="w-px h-10 bg-white/5" />
                      <div className="text-center xl:text-left">
                        <p className="text-[8px] uppercase text-gray-500 font-bold tracking-widest mb-1 italic whitespace-nowrap">Time / Intensity</p>
                        <p className="text-white text-2xl font-black italic flex items-center gap-2 justify-center xl:justify-start leading-none">
                          <Timer size={18} className="text-brand-blue" /> {plan.duration.split(' ')[0]}m
                        </p>
                      </div>
                    </div>
                  </div>

                  {/* Exercise List */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-10">
                    {plan.exercises.map((ex, idx) => (
                      <div 
                        key={idx}
                        className="bg-white/5 rounded-2xl p-5 flex items-center justify-between border border-white/5 group/ex hover:bg-white/10 transition-all"
                      >
                        <div className="flex items-center gap-4">
                          <div className="w-10 h-10 rounded-xl bg-brand-navy flex items-center justify-center text-brand-lime font-black text-sm group-hover/ex:bg-brand-orange transition-all border border-white/5">
                            {idx + 1}
                          </div>
                          <div>
                            <p className="text-base font-black text-white tracking-tight uppercase italic leading-none mb-1">{ex.name}</p>
                            <p className="text-[9px] text-gray-600 font-bold uppercase tracking-widest italic">{ex.type}</p>
                          </div>
                        </div>
                        <div className="bg-black/20 px-3 py-2 rounded-xl border border-white/5 text-center min-w-[70px]">
                          <span className="text-brand-orange font-black italic text-sm">{ex.reps.split(' ')[0]}</span>
                          <span className="text-[7px] font-bold text-gray-600 uppercase block leading-none mt-0.5">UNITS</span>
                        </div>
                      </div>
                    ))}
                  </div>

                  <button 
                    onClick={() => handleInitialize(plan.id)}
                    className="w-full h-16 bg-white/5 border border-white/10 hover:bg-white hover:text-brand-navy text-white rounded-xl font-bold text-[10px] uppercase tracking-widest flex items-center justify-center gap-4 transition-all italic shadow-2xl active:scale-95"
                  >
                    INITIALIZE SEQUENCE <ArrowRight size={18} />
                  </button>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>

          {error && (
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-red-500/10 border border-red-500/30 rounded-2xl p-5 flex items-center gap-4"
            >
              <div className="w-8 h-8 bg-red-500/20 rounded-lg flex items-center justify-center text-red-400 shrink-0">
                <ShieldAlert size={16} />
              </div>
              <p className="text-red-400 text-[10px] font-bold uppercase tracking-widest leading-relaxed">
                <span className="block text-white opacity-50">Transmission Error:</span>
                {error}
              </p>
            </motion.div>
          )}

          {plans.length === 0 && !loading && (
            <div className="bg-brand-navy-light rounded-[2.5rem] border-2 border-dashed border-white/5 py-24 text-center space-y-8 shadow-2xl">
              <div className="w-20 h-20 bg-brand-orange/10 rounded-full flex items-center justify-center mx-auto text-brand-orange border border-brand-orange/20">
                <Sparkles size={36} />
              </div>
              <div className="space-y-3">
                <h3 className="text-2xl font-black text-white italic tracking-tighter uppercase leading-none">Ready to Sync</h3>
                <p className="text-gray-500 max-w-sm mx-auto text-[10px] font-bold leading-relaxed uppercase tracking-widest italic">
                  Calibrate your physio metrics on the left, then click <span className="text-brand-orange">Generate Protocol</span> to start your session.
                </p>
              </div>
              <div className="flex items-center justify-center gap-6 text-[10px] font-bold text-gray-600 uppercase tracking-widest">
                {['1. Set Age/Mass', '2. Pick Goal', '3. Calibrate', '4. Deploy'].map((step, i) => (
                  <div key={i} className="flex items-center gap-2">
                    <div className="w-5 h-5 rounded-full bg-brand-orange/20 text-brand-orange flex items-center justify-center text-[8px] font-black">{i+1}</div>
                    <span>{step.split('. ')[1]}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AIWorkouts;
